version: "3"

services: 
    app:
        image: node:14-alpine 
        volumes:  
            - ".:/app"
        working_dir: "/app"
        # command: ["yarn"]
        command: >
            sh -c "yarn && yarn start"
        ports:  
            - 80:3333