 
name: Server Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log versions
        run: |
          node -v
          yarn -v

      # - name: Cache node modules
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: cache-node-module
      #   with:
      #     path: ~/.yarn-cache
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install

      - name: Deploy
        run: |
          rsync -rlh -progress ./ /app/teste-server
          cp /app/teste-server
          docker-compose down && docker-compose up -d --build

        # env:
        #   SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        #   SSH_PORT: ${{ secrets.SSH_PORT }}
        #   SSH_IP_ADDRESS: ${{ secrets.SSH_IP_ADDRESS }}
        #   SSH_USER: ${{ secrets.SSH_USER }}
        # run: |
        #   sudo apt-get install sshpass
        #   sshpass -p $SSH_PASSWORD rsync -av -e "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $SSH_PORT" ./ $SSH_USER@$SSH_IP_ADDRESS:/app/teste-server


      